name: Flutter Build APK

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    # Thiết lập thư mục làm việc mặc định cho tất cả các bước run
    defaults:
      run:
        working-directory: note_app_mobile 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
          # Quan trọng: Cần chỉ định nơi chứa pubspec.yaml để cache hoạt động đúng
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash'
          cache-path: '${{ github.workspace }}/.pub-cache'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: notely-dev-apk
          # Đường dẫn này cũng phải trỏ vào trong thư mục mobile
          path: note_app_mobile/build/app/outputs/flutter-apk/app-release.apk